import org.junit.*;
import static org.junit.Assert.*;

public class RoboCourierTest {
  RoboCourier robo = new RoboCourier();

  @Test
  public void test() {
    assertEquals(0, robo.timeToDeliver(new String[]{ "FRRRF" }));
    assertEquals(4, robo.timeToDeliver(new String[]{ "FRR" }));
    assertEquals(15, robo.timeToDeliver(new String[]{ "FRRFLLFLLFRRFLF" }));

    assertEquals(17, robo.timeToDeliver(new String[]{ "RFLLF" }));
    assertEquals(0, robo.timeToDeliver(new String[]{ "FLFRRFRFRRFLLFRRF" }));
    assertEquals(44, robo.timeToDeliver(new String[]
    { "FFFFFFFFFRRFFFFFFRRFFFFF",
  "FLLFFFFFFLLFFFFFFRRFFFF" }));
    assertEquals(24, robo.timeToDeliver(new String[]
    { "RFLLFLFLFRFRRFFFRFFRFFRRFLFFRLRRFFLFFLFLLFRFLFLRFF",
  "RFFLFLFFRFFLLFLLFRFRFLRLFLRRFLRFLFFLFFFLFLFFRLFRLF",
  "LLFLFLRLRRFLFLFRLFRF" }));
    assertEquals(169, robo.timeToDeliver(new String[]
    { "LLFLFRLRRLRFFLRRRRFFFLRFFRRRLLFLFLLRLRFFLFRRFFFLFL",
  "RLFFRRLRLRRFFFLLLRFRLLRFFLFRLFRRFRRRFRLRLRLFFLLFLF",
  "FRFLRFRRLLLRFFRRRLRFLFRRFLFFRLFLFLFRLLLLFRLLRFLLLF",
  "FFLFRFRRFLLFFLLLFFRLLFLRRFRLFFFRRFFFLLRFFLRFRRRLLR",
  "FFFRRLLFLLRLFRRLRLLFFFLFLRFFRLRLLFLRLFFLLFFLLFFFRR",
  "LRFRRFLRRLRRLRFFFLLLLRRLRFFLFRFFRLLRFLFRRFLFLFFLFR",
  "RFRRLRRFLFFFLLRFLFRRFRFLRLRLLLLFLFFFLFRLLRFRLFRLFR",
  "LLFLFRLFFFFFFFRRLRLRLLRFLRLRRRRRRRRLFLFLFLRFLFRLFF",
  "RLFRRLLRRRRFFFRRRLLLLRRLFFLLLLLRFFFFRFRRLRRRFFFLLF",
  "FFFFLRRLRFLLRRLRLRFRRRRLFLLRFLRRFFFRFRLFFRLLFFRRLL" }));
  }
}
